spring.application.name=finam

spring.datasource.url=jdbc:h2:file:./testdb;DB_CLOSE_ON_EXIT=FALSE;
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa

server.tomcat.threads.max=1
spring.lifecycle.timeout-per-shutdown-phase=2s


# gRPC API
finam.grpc.host=api.finam.ru
finam.grpc.port=443
finam.grpc.use-tls=true


# REST API
finam.rest.base-url=https://api.finam.ru
finam.rest.timeout=5000

spring.grpc.client.default-channel.address=api.finam.ru:443
spring.grpc.client.default-channel.negotiation-type=tls

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.ru.nuclearius.finam.grpc.JwtRenewalService=DEBUG
logging.level.ru.nuclearius.finam.service.observer.QuoteObserver=INFO
logging.level.ru.nuclearius.finam.service=DEBUG
logging.level.ru.nuclearius.finam.subscriber.AbstractBackoffObserver=DEBUG
logging.level.ru.nuclearius.finam.streamer=DEBUG