spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.ru.nuclearius.finam.grpc.JwtRenewalService=DEBUG
logging.level.ru.nuclearius.finam.service.observer.QuoteObserver=INFO
logging.level.ru.nuclearius.finam.service=INFO
logging.level.ru.nuclearius.finam.subscriber.AbstractBackoffObserver=DEBUG
logging.level.ru.nuclearius.finam.streamer=DEBUG