spring.application.name=finam
spring.profiles.active=@springProfiles@

spring.datasource.url=jdbc:h2:file:./testdb;DB_CLOSE_ON_EXIT=FALSE;
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa

server.shutdown=immediate
server.tomcat.threads.max=1
spring.lifecycle.timeout-per-shutdown-phase=2s

# gRPC API
finam.grpc.host=api.finam.ru
finam.grpc.port=443
finam.grpc.use-tls=true

springdoc.show-login-endpoint=true
spring.mvc.pathmatch.matching-strategy=ant-path-matcher

# REST API
finam.rest.base-url=https://api.finam.ru
finam.rest.timeout=5000

spring.grpc.client.default-channel.address=api.finam.ru:443
spring.grpc.client.default-channel.negotiation-type=tls

spring.cache.caffeine.spec=expireAfterWrite=1m,maximumSize=5000
# level.com.github.ben-manes.caffeine=DEBUG
# logging.level.org.springframework.cache=TRACE
server.error.include-message=always