/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/trade-groups/path/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/strategies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["byId"];
        put: operations["update_1"];
        post?: never;
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analysis/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["byId_1"];
        put: operations["update_2"];
        post?: never;
        delete: operations["delete_1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trade-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["all"];
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trade-groups/{id}/toggle-active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["toggleActiveObserver"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trade-groups/{id}/calculate-reference-offsets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["calculateReferenceOffsets"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/strategies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["all_1"];
        put?: never;
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/strategies/{id}/optimize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["optimize"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/strategies/{id}/backtest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["backtest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/spreads/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["stop"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/spreads/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["start"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["all_2"];
        put?: never;
        post: operations["create_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trade-groups/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["byId_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trade-groups/{id}/traded-assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["tradedAssets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trade-groups/{id}/reference-assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["referenceAssets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trade-groups/{id}/reference-assets/bars": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["referenceAssetsBars"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/strategies/{id}/parameters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["strategyParameters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/strategies/{id}/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["assets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/spreads/symbols": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["symbols"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/spreads/subcribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Subscribe to quotes via SSE */
        get: operations["subscribe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/spreads/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/finam/token-details": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["tokenDetails"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/finam/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["assets_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/finam/assets/{symbol}/subcribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Subscribe to quotes via SSE */
        get: operations["subscribeToAsset"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/finam/assets/{symbol}/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["orders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/finam/assets/{symbol}/bars": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["bars"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/finam/assets/bars": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["assetsBars"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/finam/accounts/{accountId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAccount"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/finam/accounts/{accountId}/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["accountTransactions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/finam/accounts/{accountId}/trades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["accountTrades"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analysis/{id}/relative-spreads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["relativeSpreads"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analysis/{id}/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["assets_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        username?: string;
                        password?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Asset: {
            id?: string;
            symbol?: string;
            ticker?: string;
            mic?: string;
            isin?: string;
            type?: string;
            name?: string;
        };
        Bar: {
            /** Format: date-time */
            timestamp?: string;
            open?: number;
            high?: number;
            low?: number;
            close?: number;
            volume?: number;
            /** Format: int64 */
            seconds?: number;
            /** Format: int64 */
            mills?: number;
        };
        Indicator: {
            /** Format: date-time */
            timestamp?: string;
            value?: number;
            /** Format: int64 */
            mills?: number;
        };
        TradeGroup: {
            /** Format: int32 */
            id?: number;
            name?: string;
            description?: string;
            active?: boolean;
        };
        TradeGroupDTO: {
            /** Format: int32 */
            id?: number;
            name?: string;
            description?: string;
            active?: boolean;
            tradedAssets?: components["schemas"]["TradeGroupTradedAssetDTO"][];
            referenceAssets?: components["schemas"]["TradeGroupReferenceAssetDTO"][];
        };
        TradeGroupReferenceAssetDTO: {
            /** @enum {string} */
            changeStatus?: "NEW" | "UPDATED" | "DELETED";
            /** Format: int32 */
            id?: number;
            tradeGroup?: components["schemas"]["TradeGroup"];
            asset?: components["schemas"]["Asset"];
            priceOffset?: number;
            lineColor?: string;
            /** Format: int32 */
            lineWidth?: number;
            enabled?: boolean;
            /** Format: int32 */
            panelNum?: number;
            bars?: components["schemas"]["Bar"][];
            sma?: components["schemas"]["Indicator"][];
        };
        TradeGroupTradedAssetDTO: {
            /** @enum {string} */
            changeStatus?: "NEW" | "UPDATED" | "DELETED";
            /** Format: int32 */
            id?: number;
            tradeGroup?: components["schemas"]["TradeGroup"];
            asset?: components["schemas"]["Asset"];
            lineColor?: string;
            /** Format: int32 */
            lineWidth?: number;
            enabled?: boolean;
        };
        StrategyAssetDto: {
            /** @enum {string} */
            changeStatus?: "NEW" | "UPDATED" | "DELETED";
            /** Format: int32 */
            id?: number;
            asset?: components["schemas"]["Asset"];
            lineColor?: string;
            /** Format: int32 */
            lineWidth?: number;
        };
        StrategyDto: {
            name?: string;
            assets?: components["schemas"]["StrategyAssetDto"][];
        };
        Strategy: {
            /** Format: int32 */
            id?: number;
            name?: string;
        };
        AnalysisAssetDTO: {
            /** @enum {string} */
            changeStatus?: "NEW" | "UPDATED" | "DELETED";
            /** Format: int32 */
            id?: number;
            asset?: components["schemas"]["Asset"];
            lineColor?: string;
            /** Format: int32 */
            lineWidth?: number;
            enabled?: boolean;
            /** Format: int32 */
            panelIndex?: number;
        };
        AnalysisDTO: {
            name?: string;
            assets?: components["schemas"]["AnalysisAssetDTO"][];
            /** Format: int32 */
            averageDays?: number;
        };
        Analysis: {
            /** Format: int32 */
            id?: number;
            name?: string;
            /** Format: int32 */
            averageDays?: number;
        };
        OptimizerStrategyParameter: {
            id?: string;
        } & (components["schemas"]["RangeOptimizerStrategyParameter"] | components["schemas"]["ValuesOptimizerStrategyParameter"]);
        RangeOptimizerStrategyParameter: components["schemas"]["OptimizerStrategyParameter"] & {
            from?: number;
            to?: number;
            step?: number;
        };
        ValuesOptimizerStrategyParameter: components["schemas"]["OptimizerStrategyParameter"] & {
            options?: string[];
        };
        OptimizationResult: {
            parameters?: {
                [key: string]: string;
            };
            value?: number;
        };
        BacktestResult: {
            series?: components["schemas"]["ChartBacktestSeries"][];
        };
        ChartBacktestSeries: {
            id?: string;
            lineColor?: string;
            /** Format: int32 */
            lineWidth?: number;
            name?: string;
            enabled?: boolean;
            /** Format: int32 */
            panelNum?: number;
            values?: components["schemas"]["Bar"][];
            indicators?: components["schemas"]["ChartIndicatorSeries"][];
            trades?: components["schemas"]["ChartSeriesMarker"][];
            statistics?: {
                [key: string]: unknown;
            };
            normalDistribution?: components["schemas"]["Point"][];
        };
        ChartIndicatorSeries: {
            id?: string;
            lineColor?: string;
            /** Format: int32 */
            lineWidth?: number;
            name?: string;
            enabled?: boolean;
            /** Format: int32 */
            panelNum?: number;
            values?: components["schemas"]["ChartIndicatorValue"][];
        };
        ChartIndicatorValue: {
            /** Format: date-time */
            timestamp?: string;
            value?: number;
            /** Format: int64 */
            seconds?: number;
        };
        ChartSeriesMarker: {
            /** Format: date-time */
            timestamp?: string;
            /** @enum {string} */
            action?: "BUY" | "SELL";
            price?: number;
            /** Format: int64 */
            seconds?: number;
        };
        Point: {
            /** Format: double */
            x?: number;
            /** Format: double */
            y?: number;
        };
        PageMetadata: {
            /** Format: int64 */
            size?: number;
            /** Format: int64 */
            number?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int64 */
            totalPages?: number;
        };
        PagedModelTradeGroup: {
            content?: components["schemas"]["TradeGroup"][];
            page?: components["schemas"]["PageMetadata"];
        };
        TradeGroupTradedAsset: {
            /** Format: int32 */
            id?: number;
            tradeGroup?: components["schemas"]["TradeGroup"];
            asset?: components["schemas"]["Asset"];
            lineColor?: string;
            /** Format: int32 */
            lineWidth?: number;
            enabled?: boolean;
        };
        TradeGroupReferenceAsset: {
            /** Format: int32 */
            id?: number;
            tradeGroup?: components["schemas"]["TradeGroup"];
            asset?: components["schemas"]["Asset"];
            priceOffset?: number;
            lineColor?: string;
            /** Format: int32 */
            lineWidth?: number;
            enabled?: boolean;
            /** Format: int32 */
            panelNum?: number;
        };
        ChartBarSeries: {
            id?: string;
            lineColor?: string;
            /** Format: int32 */
            lineWidth?: number;
            name?: string;
            enabled?: boolean;
            /** Format: int32 */
            panelNum?: number;
            values?: components["schemas"]["Bar"][];
        };
        PagedModelStrategy: {
            content?: components["schemas"]["Strategy"][];
            page?: components["schemas"]["PageMetadata"];
        };
        StrategyParameter: {
            id?: string;
            name?: string;
            /** @enum {string} */
            type?: "INTEGER" | "DOUBLE" | "STRING" | "ENUM";
            options?: {
                [key: string]: string;
            };
        };
        StrategyAsset: {
            /** Format: int32 */
            id?: number;
            strategy?: components["schemas"]["Strategy"];
            asset?: components["schemas"]["Asset"];
            lineColor?: string;
            /** Format: int32 */
            lineWidth?: number;
        };
        Order: {
            accountId?: string;
            symbol?: string;
            quantity?: number;
            /** @enum {string} */
            side?: "SIDE_UNSPECIFIED" | "SIDE_BUY" | "SIDE_SELL" | "UNRECOGNIZED";
            /** @enum {string} */
            type?: "ORDER_TYPE_UNSPECIFIED" | "ORDER_TYPE_MARKET" | "ORDER_TYPE_LIMIT" | "ORDER_TYPE_STOP" | "ORDER_TYPE_STOP_LIMIT" | "ORDER_TYPE_MULTI_LEG" | "UNRECOGNIZED";
            /** @enum {string} */
            timeInForce?: "TIME_IN_FORCE_UNSPECIFIED" | "TIME_IN_FORCE_DAY" | "TIME_IN_FORCE_GOOD_TILL_CANCEL" | "TIME_IN_FORCE_GOOD_TILL_CROSSING" | "TIME_IN_FORCE_EXT" | "TIME_IN_FORCE_ON_OPEN" | "TIME_IN_FORCE_ON_CLOSE" | "TIME_IN_FORCE_IOC" | "TIME_IN_FORCE_FOK" | "UNRECOGNIZED";
            limitPrice?: number;
            stopPrice?: number;
            /** @enum {string} */
            stopCondition?: "STOP_CONDITION_UNSPECIFIED" | "STOP_CONDITION_LAST_UP" | "STOP_CONDITION_LAST_DOWN" | "UNRECOGNIZED";
            clientOrderId?: string;
            /** @enum {string} */
            validBefore?: "VALID_BEFORE_UNSPECIFIED" | "VALID_BEFORE_END_OF_DAY" | "VALID_BEFORE_GOOD_TILL_CANCEL" | "VALID_BEFORE_GOOD_TILL_DATE" | "UNRECOGNIZED";
            comment?: string;
        };
        OrderState: {
            orderId?: string;
            execId?: string;
            /** @enum {string} */
            status?: "ORDER_STATUS_UNSPECIFIED" | "ORDER_STATUS_NEW" | "ORDER_STATUS_PARTIALLY_FILLED" | "ORDER_STATUS_FILLED" | "ORDER_STATUS_DONE_FOR_DAY" | "ORDER_STATUS_CANCELED" | "ORDER_STATUS_REPLACED" | "ORDER_STATUS_PENDING_CANCEL" | "ORDER_STATUS_REJECTED" | "ORDER_STATUS_SUSPENDED" | "ORDER_STATUS_PENDING_NEW" | "ORDER_STATUS_EXPIRED" | "ORDER_STATUS_FAILED" | "ORDER_STATUS_FORWARDING" | "ORDER_STATUS_WAIT" | "ORDER_STATUS_DENIED_BY_BROKER" | "ORDER_STATUS_REJECTED_BY_EXCHANGE" | "ORDER_STATUS_WATCHING" | "ORDER_STATUS_EXECUTED" | "ORDER_STATUS_DISABLED" | "ORDER_STATUS_LINK_WAIT" | "ORDER_STATUS_SL_GUARD_TIME" | "ORDER_STATUS_SL_EXECUTED" | "ORDER_STATUS_SL_FORWARDING" | "ORDER_STATUS_TP_GUARD_TIME" | "ORDER_STATUS_TP_EXECUTED" | "ORDER_STATUS_TP_CORRECTION" | "ORDER_STATUS_TP_FORWARDING" | "ORDER_STATUS_TP_CORR_GUARD_TIME" | "UNRECOGNIZED";
            order?: components["schemas"]["Order"];
            /** Format: date-time */
            transactAt?: string;
            /** Format: date-time */
            acceptAt?: string;
            /** Format: date-time */
            withdrawAt?: string;
            initialQuantity?: number;
            executedQuantity?: number;
            remainingQuantity?: number;
        };
        MDPermission: {
            /** @enum {string} */
            quoteLevel?: "QUOTE_LEVEL_UNSPECIFIED" | "QUOTE_LEVEL_LAST_PRICE" | "QUOTE_LEVEL_BEST_BID_OFFER" | "QUOTE_LEVEL_DEPTH_OF_MARKET" | "QUOTE_LEVEL_DEPTH_OF_BOOK" | "QUOTE_LEVEL_ACCESS_FORBIDDEN" | "UNRECOGNIZED";
            /** Format: int32 */
            delayMinutes?: number;
            mic?: string;
            country?: string;
            continent?: string;
            worldwide?: boolean;
        };
        TokenDetails: {
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            expiresAt?: string;
            mdPermissions?: components["schemas"]["MDPermission"][];
            accountIds?: string[];
            readonly?: boolean;
            active?: boolean;
        };
        PagedModelAsset: {
            content?: components["schemas"]["Asset"][];
            page?: components["schemas"]["PageMetadata"];
        };
        Account: {
            accountId?: string;
            type?: string;
            status?: string;
            equity?: number;
            unrealizedProfit?: number;
            positions?: components["schemas"]["Position"][];
            cash?: components["schemas"]["Money"][];
            portfolioMc?: components["schemas"]["PortfolioMC"];
            portfolioForts?: components["schemas"]["PortfolioForts"];
            /** Format: date-time */
            openAccountDate?: string;
            /** Format: date-time */
            firstTradeDate?: string;
            /** Format: date-time */
            firstNonTradeDate?: string;
        };
        Money: {
            currencyCode?: string;
            /** Format: int64 */
            units?: number;
            /** Format: int32 */
            nanos?: number;
        };
        PortfolioForts: {
            availableCash?: number;
            moneyReserved?: number;
        };
        PortfolioMC: {
            availableCash?: number;
            initialMargin?: number;
            maintenanceMargin?: number;
        };
        Position: {
            symbol?: string;
            quantity?: number;
            averagePrice?: number;
            currentPrice?: number;
            maintenanceMargin?: number;
            dailyPnl?: number;
            unrealizedPnl?: number;
        };
        TradeInfo: {
            size?: number;
            price?: number;
            accruedInterest?: number;
        };
        Transaction: {
            id?: string;
            /** @enum {string} */
            transactionCategory?: "OTHERS" | "DEPOSIT" | "WITHDRAW" | "INCOME" | "COMMISSION" | "TAX" | "INHERITANCE" | "TRANSFER" | "CONTRACT_TERMINATION" | "OUTCOMES" | "FINE" | "LOAN" | "UNRECOGNIZED";
            /** Format: date-time */
            timestamp?: string;
            symbol?: string;
            change?: components["schemas"]["TypeMoney"];
            trade?: components["schemas"]["TradeInfo"];
            category?: string;
            transactionName?: string;
            changeQty?: number;
        };
        TypeMoney: {
            currencyCode?: string;
            units?: string;
            /** Format: int32 */
            nanos?: number;
        };
        Trade: {
            tradeId: string;
            symbol: string;
            price?: number;
            size?: number;
            /** @enum {string} */
            side?: "SIDE_UNSPECIFIED" | "SIDE_BUY" | "SIDE_SELL" | "UNRECOGNIZED";
            /** Format: date-time */
            timestamp?: string;
            orderId?: string;
            accountId?: string;
            comment?: string;
            /** Format: int64 */
            seconds?: number;
            /** Format: int64 */
            mills?: number;
            sum?: number;
        };
        TradeHistory: {
            trades?: components["schemas"]["Trade"][];
        };
        PagedModelAnalysis: {
            content?: components["schemas"]["Analysis"][];
            page?: components["schemas"]["PageMetadata"];
        };
        ChartBarSeriesWithTrades: {
            id?: string;
            lineColor?: string;
            /** Format: int32 */
            lineWidth?: number;
            name?: string;
            enabled?: boolean;
            /** Format: int32 */
            panelNum?: number;
            values?: components["schemas"]["Bar"][];
            trades?: components["schemas"]["Trade"][];
        };
        AnalysisAsset: {
            /** Format: int32 */
            id?: number;
            analysis?: components["schemas"]["Analysis"];
            asset?: components["schemas"]["Asset"];
            lineColor?: string;
            /** Format: int32 */
            lineWidth?: number;
            enabled?: boolean;
            /** Format: int32 */
            panelIndex?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TradeGroupDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TradeGroup"];
                };
            };
        };
    };
    byId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Strategy"];
                };
            };
        };
    };
    update_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StrategyDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Strategy"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    byId_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Analysis"];
                };
            };
        };
    };
    update_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalysisDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Analysis"];
                };
            };
        };
    };
    delete_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    all: {
        parameters: {
            query?: {
                q?: string;
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedModelTradeGroup"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TradeGroupDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TradeGroup"];
                };
            };
        };
    };
    toggleActiveObserver: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": boolean;
                };
            };
        };
    };
    calculateReferenceOffsets: {
        parameters: {
            query: {
                timeFrame: "TIME_FRAME_UNSPECIFIED" | "TIME_FRAME_M1" | "TIME_FRAME_M5" | "TIME_FRAME_M15" | "TIME_FRAME_M30" | "TIME_FRAME_H1" | "TIME_FRAME_H2" | "TIME_FRAME_H4" | "TIME_FRAME_H8" | "TIME_FRAME_D" | "TIME_FRAME_W" | "TIME_FRAME_MN" | "TIME_FRAME_QR" | "UNRECOGNIZED";
                startTime: string;
                endTime: string;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    all_1: {
        parameters: {
            query?: {
                q?: string;
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedModelStrategy"];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StrategyDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Strategy"];
                };
            };
        };
    };
    optimize: {
        parameters: {
            query: {
                assetId: string;
                timeFrame: "TIME_FRAME_UNSPECIFIED" | "TIME_FRAME_M1" | "TIME_FRAME_M5" | "TIME_FRAME_M15" | "TIME_FRAME_M30" | "TIME_FRAME_H1" | "TIME_FRAME_H2" | "TIME_FRAME_H4" | "TIME_FRAME_H8" | "TIME_FRAME_D" | "TIME_FRAME_W" | "TIME_FRAME_MN" | "TIME_FRAME_QR" | "UNRECOGNIZED";
                startTime: string;
                endTime: string;
                transactionCost: number;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OptimizerStrategyParameter"][];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OptimizationResult"];
                };
            };
        };
    };
    backtest: {
        parameters: {
            query: {
                assets: string[];
                timeFrame: "TIME_FRAME_UNSPECIFIED" | "TIME_FRAME_M1" | "TIME_FRAME_M5" | "TIME_FRAME_M15" | "TIME_FRAME_M30" | "TIME_FRAME_H1" | "TIME_FRAME_H2" | "TIME_FRAME_H4" | "TIME_FRAME_H8" | "TIME_FRAME_D" | "TIME_FRAME_W" | "TIME_FRAME_MN" | "TIME_FRAME_QR" | "UNRECOGNIZED";
                startTime: string;
                endTime: string;
                transactionCost: number;
                distributionMa: number;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BacktestResult"];
                };
            };
        };
    };
    stop: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    start: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    all_2: {
        parameters: {
            query?: {
                q?: string;
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedModelAnalysis"];
                };
            };
        };
    };
    create_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalysisDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Analysis"];
                };
            };
        };
    };
    byId_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TradeGroupDTO"];
                };
            };
        };
    };
    tradedAssets: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TradeGroupTradedAsset"][];
                };
            };
        };
    };
    referenceAssets: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TradeGroupReferenceAsset"][];
                };
            };
        };
    };
    referenceAssetsBars: {
        parameters: {
            query: {
                timeFrame: "TIME_FRAME_UNSPECIFIED" | "TIME_FRAME_M1" | "TIME_FRAME_M5" | "TIME_FRAME_M15" | "TIME_FRAME_M30" | "TIME_FRAME_H1" | "TIME_FRAME_H2" | "TIME_FRAME_H4" | "TIME_FRAME_H8" | "TIME_FRAME_D" | "TIME_FRAME_W" | "TIME_FRAME_MN" | "TIME_FRAME_QR" | "UNRECOGNIZED";
                startTime: string;
                endTime: string;
                smaBarCount?: number;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ChartBarSeries"][];
                };
            };
        };
    };
    strategyParameters: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StrategyParameter"][];
                };
            };
        };
    };
    assets: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StrategyAsset"][];
                };
            };
        };
    };
    symbols: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string[];
                };
            };
        };
    };
    subscribe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream of quotes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
        };
    };
    status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": boolean;
                };
            };
        };
    };
    findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OrderState"][];
                };
            };
        };
    };
    tokenDetails: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TokenDetails"];
                };
            };
        };
    };
    assets_1: {
        parameters: {
            query?: {
                q?: string;
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedModelAsset"];
                };
            };
        };
    };
    subscribeToAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream of quotes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
        };
    };
    orders: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OrderState"][];
                };
            };
        };
    };
    bars: {
        parameters: {
            query: {
                timeFrame: "TIME_FRAME_UNSPECIFIED" | "TIME_FRAME_M1" | "TIME_FRAME_M5" | "TIME_FRAME_M15" | "TIME_FRAME_M30" | "TIME_FRAME_H1" | "TIME_FRAME_H2" | "TIME_FRAME_H4" | "TIME_FRAME_H8" | "TIME_FRAME_D" | "TIME_FRAME_W" | "TIME_FRAME_MN" | "TIME_FRAME_QR" | "UNRECOGNIZED";
                startTime: string;
                endTime: string;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Bar"][];
                };
            };
        };
    };
    assetsBars: {
        parameters: {
            query: {
                symbols: string[];
                timeFrame: "TIME_FRAME_UNSPECIFIED" | "TIME_FRAME_M1" | "TIME_FRAME_M5" | "TIME_FRAME_M15" | "TIME_FRAME_M30" | "TIME_FRAME_H1" | "TIME_FRAME_H2" | "TIME_FRAME_H4" | "TIME_FRAME_H8" | "TIME_FRAME_D" | "TIME_FRAME_W" | "TIME_FRAME_MN" | "TIME_FRAME_QR" | "UNRECOGNIZED";
                startTime: string;
                endTime: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: components["schemas"]["Bar"][];
                    };
                };
            };
        };
    };
    getAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Account"];
                };
            };
        };
    };
    accountTransactions: {
        parameters: {
            query?: {
                limit?: number;
                startTime?: string;
                endTime?: string;
            };
            header?: never;
            path: {
                accountId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Transaction"][];
                };
            };
        };
    };
    accountTrades: {
        parameters: {
            query?: {
                limit?: number;
                startTime?: string;
                endTime?: string;
            };
            header?: never;
            path: {
                accountId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TradeHistory"];
                };
            };
        };
    };
    relativeSpreads: {
        parameters: {
            query: {
                timeFrame: "TIME_FRAME_UNSPECIFIED" | "TIME_FRAME_M1" | "TIME_FRAME_M5" | "TIME_FRAME_M15" | "TIME_FRAME_M30" | "TIME_FRAME_H1" | "TIME_FRAME_H2" | "TIME_FRAME_H4" | "TIME_FRAME_H8" | "TIME_FRAME_D" | "TIME_FRAME_W" | "TIME_FRAME_MN" | "TIME_FRAME_QR" | "UNRECOGNIZED";
                startTime: string;
                endTime: string;
                averageTimeFrame: "TIME_FRAME_UNSPECIFIED" | "TIME_FRAME_M1" | "TIME_FRAME_M5" | "TIME_FRAME_M15" | "TIME_FRAME_M30" | "TIME_FRAME_H1" | "TIME_FRAME_H2" | "TIME_FRAME_H4" | "TIME_FRAME_H8" | "TIME_FRAME_D" | "TIME_FRAME_W" | "TIME_FRAME_MN" | "TIME_FRAME_QR" | "UNRECOGNIZED";
                averageStartTime: string;
                averageEndTime: string;
                zEstimate?: boolean;
                withTrades?: boolean;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ChartBarSeriesWithTrades"][];
                };
            };
        };
    };
    assets_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AnalysisAsset"][];
                };
            };
        };
    };
}
